name: Test
on:
  push:
    branches:
      - renovate/**
      - changeset-release/**
  pull_request:
    branches-ignore:
      - renovate/**
      - changeset-release/**
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  succeed:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: install dependencies
        run: pnpm install
      - name: make sure it builds
        run: pnpm build
